<?php
defined('BASEPATH') OR exit('No direct script access allowed');

require APPPATH . 'libraries/REST_Controller.php';

class Facebook extends REST_Controller {

	public function __construct(){
		
		parent::__construct();
		$this->load->helper('url');
	}
	
	public function index(){}
	
	
	// Get playlist detail using youtube channel id 
	/* 
		Parameter :
			channel_id = youtube channel id
			key = access_token generated by devloper account.
	*/
	
}
?>